### ISSUE TITLE
How to update the manager?

### ISSUE THREAD

**Issue by TheMayor77** [SutandoTsukai181/RyuModManager#12]
I had version 1.7 installed and I'm trying to get 2.1 to work but whenever I run the new Mod Manager it says something about an external mods folder being detected and having to run it in CLI mode. I haven't deleted the old version yet by the way because I wasn't sure if I should. What can I do to fix this?

Thanks

**Comment by mosamadeeb** [comment]
You can just remove the old EXE and install the the new version of RMM.

> it says something about an external mods folder being detected

This means that you were using Vortex (or Mod Organizer) before, and should use it instead of running RMM. If you don't want to use Vortex anymore, remove the `_externalMods` folder inside your `mods` folder, and run RMM again. This will remove your old mods, however.
