### ISSUE TITLE
Access is denied (xbox pc launcher, insider update)

### ISSUE THREAD

**Issue by XinaTheThird** [SutandoTsukai181/RyuModManager#9]
in the latest version of the mod manager whenever i try to launch RMM it says that access is to the specified game folder is denied as shown in the screenshot below
![unknown-9](https://user-images.githubusercontent.com/102587311/170008896-567e0c56-4219-44cc-8e6c-a9dfd191ee5b.png)
i tried running it as an administrator but all i get is the same result. 
I tried running the game to see if the mods work and it gives me this error (in the previous version of the MM it used to give me the assertion fail error, so this maybe is a step forward)
![error](https://user-images.githubusercontent.com/102587311/170009316-44c17101-d946-4989-9494-41f8200bdfee.PNG)
and when i close the game it doesnt shut well and keeps running in background
![runn](https://user-images.githubusercontent.com/102587311/170009472-256b3b74-6f09-44d5-af31-e15f03b18503.PNG)
any ideas on how can i fix this ?
Thanks.

**Comment by mosamadeeb** [comment]
The error in the first pic is my fault for not handling exceptions in the new EXE checking feature. You can avoid this error for now by disabling `ShowWarnings` in the YakuzaParless.INI

That being said, that feature was added specifically to show a warning if the game might be unsupported, which is the case for UWP (Win10) versions of the games. Since you already got the "assertion failed" error before, that means the mod loader will not work.

**Comment by XinaTheThird** [comment]
> The error in the first pic is my fault for not handling exceptions in the new EXE checking feature. You can avoid this error for now by disabling `ShowWarnings` in the YakuzaParless.INI.

since the issue is with the exe, does that mean if i install a steam version exe file the mods will run ?

**Comment by mosamadeeb** [comment]
Only the Steam version is supported for now, so yeah, you will need a Steam installation of the game. Simply copying the Steam EXE to the existing game will not work.
